### ISSUE TITLE
Inkorrektes Lösen des Haupträstels

### ISSUE THREAD

**Issue by SamuelHoppe** [hgs-itg23/EscapeRiddle#13]
Der Spieler möchte, dass sich die "Geschafft" Seite nicht öffnet, um das Richtige Lösungswort eingeben zu können.

### Abnahmekriterien

- "Falsch" auf dem bildschirm angezigt wird.
- sich nicht die nächste Seite öffnet.
- der Spieler einen neuen Versuch erhält.

**Comment by BlackArroww** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/hgs-itg23-EscapeRiddle-6214fc7eb82a6d0012702557/issues/hgs-itg23/EscapeRiddle/13?planning-poker) with ZenHub @Asusgamer40
