### ISSUE TITLE
WEBSITE - Regeln

### ISSUE THREAD

**Issue by BlackArroww** [hgs-itg23/EscapeRiddle#19]
Der Spieler möchte, dass er die Regeln bzw den Spielverlauf auf der Website nachlesen.

### Abnahmekriterien

- die Regeln bzw der Spielverlauf auf der Website angezeigt wird

**Comment by Asusgamer40** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/hgs-itg23-EscapeRiddle-6214fc7eb82a6d0012702557/issues/hgs-itg23/EscapeRiddle/19?planning-poker) with ZenHub @BlackArroww
