### ISSUE TITLE
Objektabhängiges Rätsel

### ISSUE THREAD

**Issue by Asusgamer40** [hgs-itg23/EscapeRiddle#2]
Der Spieler möchte nach anklicken eines bestimmten Objektes das zugehörige Rätsel angezeigt bekommen, um dies zu lösen.

### Abnahmekriterien

- wird das richtige Rätsel abghängig vom angeklickten Objekt angezeigt

**Comment by BlackArroww** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/hgs-itg23-EscapeRiddle-6214fc7eb82a6d0012702557/issues/hgs-itg23/EscapeRiddle/2?planning-poker) with ZenHub @Asusgamer40
