### ISSUE TITLE
Korrektes Abschließen eines Rätsels

### ISSUE THREAD

**Issue by Asusgamer40** [hgs-itg23/EscapeRiddle#3]
Der Spieler möchte nach Abschluss eines richtig gelösten Rätsels, dies angezeigt bekommen, um das nächste Rätsel starten zu können.

### Abnahmekriterien

- die nächste Seite geöffnet wird
- im Textfeld "Richtig" angezeigt wird
- das Rätsel richtig gelöst wurde

**Comment by BlackArroww** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/hgs-itg23-EscapeRiddle-6214fc7eb82a6d0012702557/issues/hgs-itg23/EscapeRiddle/3?planning-poker) with ZenHub @Asusgamer40
