### ISSUE TITLE
Inkorrektes Abschließen eines Rätsels

### ISSUE THREAD

**Issue by Asusgamer40** [hgs-itg23/EscapeRiddle#4]
Der Spieler möchte nach einer falschen Eingabe darüber informiert werden, um einen neuen Versuch zu starten.

### Abnahmekriterien

- die gleiche Seite angezeigt wird
- im Textfeld "Falsch" angezeigt wird
- die Eingabe falsch ist
- man das Rätsel erneut lösen kann

**Comment by BlackArroww** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/hgs-itg23-EscapeRiddle-6214fc7eb82a6d0012702557/issues/hgs-itg23/EscapeRiddle/4?planning-poker) with ZenHub @Asusgamer40
