### ISSUE TITLE
WEBSITE - Website Aufteilung

### ISSUE THREAD

**Issue by BlackArroww** [hgs-itg23/EscapeRiddle#9]
Der User möchte eine struktorierte Website, um sich leicht zurecht zu finden.

### Abnahmekriterien

- die Verlinkkungen funktionieren
- es klar gekennzeichnete Verlinkung zu anderen Seiten der Website gibt
- die Verlinkung HAUPTSEITE zur HAUPTSEITE führt
- die Verlinkung SPIEL zum SPIEL führt
- die Verlinkung REGELN zu den REGELN führt

**Comment by Asusgamer40** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/hgs-itg23-EscapeRiddle-6214fc7eb82a6d0012702557/issues/hgs-itg23/EscapeRiddle/9?planning-poker) with ZenHub @BlackArroww
